### ISSUE TITLE
[Proposal] Request/Response File Naming

### ISSUE THREAD

**Issue by gperdomor** [vapor-community/styleguide#5]
I quote...

> Files that contain objects used to decode body content from a request should be appended with Request. For example, LoginRequest. Files that contain objects used to encode body content to a response should be appended with Response. For example, LoginResponse

Now... When you have multiple models maybe you will ended with a list of file similar to this:

```
├── Requests
    ├── CreateProjectRequest
    ├── CreateTodoRequest
    ├── CreateUserRequest
    ├── UpdateProjectRequest
    ├── UpdateTodoRequest
    └── UpdateUserRequest
```

My proposal is to group all related request by model in a file named `Model+Requests.swift`, for example:

```swift
// Todo+Requests.swift - Version 1

import Vapor

extension Todo {
    struct CreateRequest: Content {
        var title: String
        var body: String?
    }
    
    convenience init(from payload: CreateRequest) {
        self.init(title: payload.title, body: payload.body)
    }
    
    struct UpdateRequest: Content {
        var title: String
        var body: String?
        var completed: Bool
    }
}
```

or...

```swift
// Todo+Requests.swift - Version 2

import Vapor

struct CreateTodoRequest: Content {
    var title: String
    var body: String?
}

struct UpdateTodoRequest: Content {
    var title: String
    var body: String?
    var completed: Bool
}

extension Todo {    
    convenience init(from payload: CreateTodoRequest) {
        self.init(title: payload.title, body: payload.body)
    }
}
```

**Comment by jdmcd** [comment]
Personally, I'm not sure I'm a fan of option number one. I think there are some cases in which the response/request objects get very bloated. For example, even though it breaks REST principles, some apis will return the children objects along with the parent object. (i.e. including all of the pets when querying for an owner). Those models can get pretty big, especially if the child object needs to be customized. This could result in large extension files that are confusing to parse through. 

I see the intention behind it, so I could get behind the addition of recommending splitting up the `Requests` and `Responses` folder into entities to keep it cleaner (i.e. you could have a `Todo` folder inside of `Requests` and `Responses` that holds all of the `Todo` entity-related encodable/decodable models)

What do you think?

**Comment by gperdomor** [comment]
Mmmm I think I can live with that 🤔...

And non fluent related requests/responses? Like `LoginRequest`for example... Where their can live? In the Requests/Responses folders without a sub folder?

**Comment by jdmcd** [comment]
That's a good question. Maybe this should be phrased as a recommendation rather than a standard? That way if a project is fluent-heavy they can lean towards entity-seperated folders and if it's not they can lean towards whichever organization method makes sense in that folder in the context of their project. What do you think?
